# Autor = Ing. Julian Ricardo Fonseca A - Consultor Senior Ansible (Entelgy)
# Fecha = 31/08/2021
---
- name: Copy script to server
  copy:
    src: files/{{ script2 }}
    dest: "/tmp/{{ script2 }}"
    mode: 0755

- name: Copy script FWAddNewAddressBlacklist_v3.sh
  copy:
    src: files/FWAddNewAddressBlacklist_v3.sh
    dest: /tmp/FWAddNewAddressBlacklist_v3.sh
    mode: 0755

- name: Copy script RunFWAddNewAddressBlacklist_v3.sh
  copy:
    src: files/RunFWAddNewAddressBlacklist_v3.sh
    dest: /tmp/RunFWAddNewAddressBlacklist_v3.sh
    mode: 0755

- name: Add Ipaddress to BlackList
  command: '/usr/bin/sh {{ ruta }}/{{ script2 }} {{ fw }} {{ addr }}'

- name: Save result
  command: 'cat {{ file }}'
  register: outIps

- name: Print added IP(s)
  debug:
    msg: "{{ outIps.stdout_lines }}"

- name: Remove Temporal Script FWAddNewAddressBlacklist_v3.sh
  file:
    path: /tmp/FWAddNewAddressBlacklist_v3.sh
    state: absent

- name: Remove Temporal Script RunFWAddNewAddressBlacklist_v3.sh
  file:
    path: /tmp/RunFWAddNewAddressBlacklist_v3.sh
    state: absent

- name: Remove temporal script "{{ script2 }}""
  file:
    path: "/tmp/{{ script2 }}"
    state: absent

- name: Remove File Temporal address2
  file:
    path: /tmp/address2
    state: absent
...
