# Autor = Ing. Julian Ricardo Fonseca A - Consultor Senior Ansible (Entelgy)
# Fecha = 01/09/2021
---
- name: Copy script to server
  copy:
    dest: "/tmp/{{ script2 }}"
    src: files/{{ script2 }}
    mode: 0755

- name: Copy script AddMultiUser.sh
  copy:
    dest: /tmp/AddMultiUser.sh
    src: files/AddMultiUser.sh
    mode: 0755

- name: Copy script CreateUsersFULL.sh
  copy:
    dest: /tmp/CreateUsersFULL.sh
    src: files/CreateUsersFULL.sh
    mode: 0755

- name: Create User(s).
  command: '/usr/bin/sh {{ ruta }}/{{ script2 }} {{ fw }} {{ group }} {{ user }}'

- name: Save result
  command: 'cat {{ file }}'
  register: outUsers

- name: Print Groups to User
  debug:
    msg: "{{ outUsers.stdout_lines }}"

- name: Delete Temporaly
  file: 
    state: absent 
    path: '{{ file }}'

- name: Remove temporal script "{{ script2 }}""
  file:
    path: "/tmp/{{ script2 }}"
    state: absent

- name: Remove temporal script AddMultiUser.sh
  file:
    path:  /tmp/AddMultiUser.sh
    state: absent

- name: Remove temporal script CreateUsersFULL.sh
  file:
    path:  /tmp/CreateUsersFULL.sh
    state: absent

...